-- MusicAPI v2 PostgreSQL schema
-- Generated from the current MySQL dump: muzik.sql
-- Structure only. Data is in data.sql.

BEGIN;

-- Table: albums
CREATE TABLE albums (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title varchar(255) NOT NULL,
    slug varchar(191) DEFAULT NULL,
    description text,
    cover_url text,
    release_date date DEFAULT NULL,
    album_type TEXT DEFAULT 'Album',
    copyright varchar(255) DEFAULT NULL,
    label varchar(255) DEFAULT NULL,
    total_tracks INTEGER DEFAULT 0,
    created_at timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp NULL DEFAULT NULL,
    PRIMARY KEY (id),
    CONSTRAINT albums_slug_unique UNIQUE (slug)
);
CREATE INDEX idx_album_title ON albums (title);
CREATE INDEX idx_album_release ON albums (release_date);
CREATE INDEX idx_albums_deleted_id ON albums (deleted_at,id);

-- Table: artist_follows
CREATE TABLE artist_follows (
    user_id INTEGER NOT NULL,
    artist_id INTEGER NOT NULL,
    created_at timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id,artist_id)
);
CREATE INDEX fk_follow_artist ON artist_follows (artist_id);

-- Table: artists
CREATE TABLE artists (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name varchar(200) NOT NULL,
    slug varchar(200) DEFAULT NULL,
    bio text,
    country varchar(100) DEFAULT NULL,
    image_url text,
    verified SMALLINT DEFAULT 0,
    monthly_listeners BIGINT DEFAULT 0,
    created_at timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp NULL DEFAULT NULL,
    PRIMARY KEY (id),
    CONSTRAINT artists_slug_unique UNIQUE (slug)
);
CREATE INDEX idx_artist_name ON artists (name);
CREATE INDEX idx_artist_verified ON artists (verified);
CREATE INDEX idx_artists_deleted_id ON artists (deleted_at,id);

-- Table: favorites
CREATE TABLE favorites (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id INTEGER NOT NULL,
    song_id INTEGER NOT NULL,
    created_at timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uk_favorite UNIQUE (user_id,song_id)
);
CREATE INDEX fk_favorite_song ON favorites (song_id);

-- Table: genres
CREATE TABLE genres (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name varchar(100) NOT NULL,
    slug varchar(100) DEFAULT NULL,
    created_at timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT genres_name_unique UNIQUE (name),
    CONSTRAINT genres_slug_unique UNIQUE (slug)
);

-- Table: history
CREATE TABLE history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id INTEGER NOT NULL,
    song_id INTEGER NOT NULL,
    played_at timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    play_duration INTEGER DEFAULT 0,
    completed SMALLINT DEFAULT 0,
    device varchar(100) DEFAULT NULL,
    PRIMARY KEY (id)
);
CREATE INDEX idx_history_user ON history (user_id);
CREATE INDEX idx_history_song ON history (song_id);
CREATE INDEX idx_history_played ON history (played_at);

-- Table: notifications
CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id INTEGER NOT NULL,
    title varchar(255) NOT NULL,
    message text NOT NULL,
    type TEXT DEFAULT 'general',
    reference_id INTEGER DEFAULT NULL,
    is_read SMALLINT DEFAULT 0,
    created_at timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);
CREATE INDEX idx_notification_user ON notifications (user_id);
CREATE INDEX idx_notification_read ON notifications (is_read);

-- Table: playlist_songs
CREATE TABLE playlist_songs (
    playlist_id INTEGER NOT NULL,
    song_id INTEGER NOT NULL,
    position INTEGER NOT NULL,
    added_at timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (playlist_id,song_id),
    CONSTRAINT uk_playlist_position UNIQUE (playlist_id,position)
);
CREATE INDEX fk_playlist_song_song ON playlist_songs (song_id);

-- Table: playlists
CREATE TABLE playlists (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id INTEGER NOT NULL,
    title varchar(255) NOT NULL,
    description text,
    cover_url text,
    is_public SMALLINT DEFAULT 1,
    total_songs INTEGER DEFAULT 0,
    created_at timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);
CREATE INDEX idx_playlist_user ON playlists (user_id);

-- Table: search_history
CREATE TABLE search_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id INTEGER NOT NULL,
    keyword varchar(255) NOT NULL,
    searched_at timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);
CREATE INDEX idx_search_user ON search_history (user_id);
CREATE INDEX idx_keyword ON search_history (keyword);
CREATE INDEX idx_searched ON search_history (searched_at);

-- Table: song_albums
CREATE TABLE song_albums (
    song_id INTEGER NOT NULL,
    album_id INTEGER NOT NULL,
    track_number INTEGER DEFAULT NULL,
    disc_number INTEGER DEFAULT 1,
    created_at timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (song_id,album_id)
);
CREATE INDEX idx_song_album_album ON song_albums (album_id);
CREATE INDEX idx_song_albums_song ON song_albums (song_id);

-- Table: song_artists
CREATE TABLE song_artists (
    song_id INTEGER NOT NULL,
    artist_id INTEGER NOT NULL,
    role TEXT NOT NULL DEFAULT 'Main',
    created_at timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (song_id,artist_id,role)
);
CREATE INDEX idx_song_artist_artist ON song_artists (artist_id);
CREATE INDEX idx_song_artists_song ON song_artists (song_id);

-- Table: song_genres
CREATE TABLE song_genres (
    song_id INTEGER NOT NULL,
    genre_id INTEGER NOT NULL,
    created_at timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (song_id,genre_id)
);
CREATE INDEX idx_song_genre_genre ON song_genres (genre_id);
CREATE INDEX idx_song_genres_song ON song_genres (song_id);

-- Table: song_views
CREATE TABLE song_views (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    song_id INTEGER NOT NULL,
    user_id INTEGER DEFAULT NULL,
    viewed_at timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    ip_address varchar(45) DEFAULT NULL,
    device varchar(100) DEFAULT NULL,
    platform varchar(50) DEFAULT NULL,
    PRIMARY KEY (id)
);
CREATE INDEX idx_song ON song_views (song_id);
CREATE INDEX idx_user ON song_views (user_id);
CREATE INDEX idx_viewed ON song_views (viewed_at);

-- Table: songs
CREATE TABLE songs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title varchar(255) NOT NULL,
    slug varchar(191) DEFAULT NULL,
    description text,
    lyrics text,
    audio_url text NOT NULL,
    cover_url text,
    duration_seconds INTEGER NOT NULL,
    language varchar(50) DEFAULT NULL,
    release_date date DEFAULT NULL,
    play_count BIGINT DEFAULT 0,
    like_count BIGINT DEFAULT 0,
    download_count BIGINT DEFAULT 0,
    is_explicit SMALLINT DEFAULT 0,
    is_active SMALLINT DEFAULT 1,
    created_at timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp NULL DEFAULT NULL,
    PRIMARY KEY (id),
    CONSTRAINT songs_slug_unique UNIQUE (slug)
);
CREATE INDEX idx_song_title ON songs (title);
CREATE INDEX idx_song_slug ON songs (slug);
CREATE INDEX idx_song_release ON songs (release_date);
CREATE INDEX idx_song_play_count ON songs (play_count);
CREATE INDEX idx_song_like_count ON songs (like_count);
CREATE INDEX idx_song_download_count ON songs (download_count);
CREATE INDEX idx_song_active ON songs (is_active);
CREATE INDEX idx_songs_deleted_id ON songs (deleted_at,id);
CREATE INDEX idx_songs_language ON songs (language);
CREATE INDEX idx_songs_active ON songs (is_active,deleted_at);

-- Table: user_settings
CREATE TABLE user_settings (
    user_id INTEGER NOT NULL,
    theme TEXT DEFAULT 'system',
    language varchar(10) DEFAULT 'en',
    stream_quality TEXT DEFAULT 'high',
    download_quality TEXT DEFAULT 'high',
    autoplay SMALLINT DEFAULT 1,
    crossfade_seconds SMALLINT DEFAULT 0,
    normalize_volume SMALLINT DEFAULT 1,
    explicit_content SMALLINT DEFAULT 1,
    created_at timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id)
);


-- Table: users
CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name varchar(150) NOT NULL,
    email varchar(150) NOT NULL,
    password_hash varchar(255) NOT NULL,
    avatar_url text,
    country varchar(100) DEFAULT NULL,
    birth_date date DEFAULT NULL,
    gender TEXT DEFAULT 'other',
    bio text,
    is_premium SMALLINT DEFAULT 0,
    status SMALLINT DEFAULT 1,
    last_login timestamp NULL DEFAULT NULL,
    created_at timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp NULL DEFAULT NULL,
    PRIMARY KEY (id),
    CONSTRAINT email UNIQUE (email)
);


COMMIT;
